name: Changelog

on:
  pull_request:
    branches:
      - master

jobs:
  changelog:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:

    - name: Check Changelog Updated
      id: checkchangelogupdated
      if: ${{ contains( github.event.pull_request.labels.*.name, 'no-changelog') != 'true' }}
      run: |
        URL="https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/${{ github.event.pull_request.number }}/files"
        FILES=$(curl -s -H 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' -X GET -G $URL | jq -r '.[] | .filename')
        echo $FILES | grep 'CHANGELOG.md'

    - name: Display Message if Changelog Missing
      if: ${{ steps.checkchangelogupdated.outcome == failure }}
      run: echo 'The changelog has not changed and the no-changelog label was not applied. Pleasee see CONTRIBUTING.md for changelog format.'

    - name: Check Changelog Contents
      id: checkchangelogcontents
      if: ${{ contains( github.event.pull_request.labels.*.name, 'no-changelog') != 'true' }}
      run: cat CHANGELOG.md | grep '## Recent Changes' && echo 'Recent Changes header found.'

    - name: Display Message if Header Missing
      if: ${{ steps.checkchangelogcontents.outcome == failure }}
      run: echo 'No recent changes header was found. Please see CONTRIBUTING.md for changelog format.'
    