name: Lint

on:
  push:
    branches-ignore:
      - 'master'
      - 'zowe-v1-lts'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install Node Package Dependencies
      run: npm ci

    - name: Lint
      run: npm run lint
