# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [8.x, 10.x, 12.x]
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci

    - run: npm run build --if-present

    - name: Unit Tests
      run: npm run test:unit -- --silent > unit-output.txt

    - name: Integration Tests
      run: npm run test:integration -- --silent > integration-output.txt

    - name: Archive Unit Test Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.os }}-${{ matrix.node-version }}-unit-test.log
        path: unit-output.txt

    - name: Archive Integration Test Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.os }}-${{ matrix.node-version }}-integration-test.log
        path: integration-output.txt