# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [8.x, 10.x, 12.x]
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: npm ci

    - run: npm run build --if-present

    - name: Unit Tests
      uses: mattallty/jest-github-actions@v1
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        test-command: "npm run test:unit"

    - name: Integration Tests
      uses: mattallty/jenkins-github-actions@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      with:
        test-command: "npm run test:integration"
    
