# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        node-version: [8.x, 10.x, 12.x]
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v2


    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}


    - name: Install Node Package Dependencies
      run: npm ci


    - name: Lint
      run: npm run lint


    - name: Build Source
      run: npm run build --if-present


    - name: Unlock Keyring
      if: matrix.os == 'ubuntu-latest'
      uses: tjohnsonBCM/unlock-keyring@master


    - name: Unit Tests
      run: npm run test:unit -- --silent

    - name: Integration Tests
      run: npm run test:integration -- --silent


    - name: Zip and Archive Results
      uses: papeloto/action-zip@v1
      with:
        files: __tests__/__results__/
        dest: results.zip
        recursive: false
      uses: actions/upload-artifact@v1
      with:
        name: ${{ matrix.os }}-${{ matrix.node-version }}-results
        path: results.zip


    - name: Check Vulnerabilities
      run: npm audit --audit-level=moderate
